[package]
name = "ffi-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45" # remove after upgrading to next version of uniffi
structopt = "0.3"
uniffi_bindgen = "0.21.0"
camino = "1.0.9"
